
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pirakavi
 */
public class NewLecturerForPG extends javax.swing.JFrame {

    /**
     * Creates new form NewLecturerForPG
     */
    public NewLecturerForPG() {
        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        subjectX = new javax.swing.JTextField();
        addX = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        emailX = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        addressX = new javax.swing.JTextArea();
        fullnameX = new javax.swing.JTextField();
        contactnoX = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        cancelX = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        facultyX = new javax.swing.JComboBox();
        yearX = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        instiX = new javax.swing.JTextField();
        qualifiX = new javax.swing.JTextField();
        subIdX = new javax.swing.JTextField();
        mainmenuX = new javax.swing.JButton();
        birthdateX = new org.jdesktop.swingx.JXDatePicker();
        genderX = new javax.swing.JComboBox();
        jLabel62 = new javax.swing.JLabel();
        fyearX = new javax.swing.JComboBox();
        jLabel63 = new javax.swing.JLabel();
        lecIdX = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        newadmin3 = new javax.swing.JLabel();
        courseX = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(0, 204, 204));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel50.setText("Full Name");

        subjectX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectXActionPerformed(evt);
            }
        });

        addX.setBackground(new java.awt.Color(0, 0, 255));
        addX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addX.setText("Add");
        addX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addXActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel51.setText("Birth Date");

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel52.setText("Subject");

        emailX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailXActionPerformed(evt);
            }
        });

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel53.setText("Address");

        addressX.setColumns(20);
        addressX.setRows(5);
        jScrollPane4.setViewportView(addressX);

        fullnameX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameXActionPerformed(evt);
            }
        });
        fullnameX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fullnameXKeyTyped(evt);
            }
        });

        contactnoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnoXActionPerformed(evt);
            }
        });
        contactnoX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactnoXKeyTyped(evt);
            }
        });

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel54.setText("E-mail ");

        cancelX.setBackground(new java.awt.Color(204, 0, 0));
        cancelX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelX.setText("Cancel");
        cancelX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelXActionPerformed(evt);
            }
        });

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel55.setText("Faculty");

        facultyX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        facultyX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "School of Business", "School of Computing", " " }));
        facultyX.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                facultyXItemStateChanged(evt);
            }
        });
        facultyX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyXActionPerformed(evt);
            }
        });

        yearX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearXActionPerformed(evt);
            }
        });

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel56.setText("Subject Id");

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel57.setText("Gender");

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel58.setText("Contact No");

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel59.setText("Institute");

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel60.setText("Year");

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel61.setText("Qualification");

        instiX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instiXActionPerformed(evt);
            }
        });

        qualifiX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qualifiXActionPerformed(evt);
            }
        });

        subIdX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subIdXActionPerformed(evt);
            }
        });

        mainmenuX.setBackground(new java.awt.Color(0, 0, 255));
        mainmenuX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainmenuX.setText("MainMenu");
        mainmenuX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainmenuX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuXActionPerformed(evt);
            }
        });

        genderX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        genderX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderXActionPerformed(evt);
            }
        });

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel62.setText("For Year");

        fyearX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fyearX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1st Year", "2nd Year", " " }));
        fyearX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fyearXActionPerformed(evt);
            }
        });

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel63.setText("Lecturer Id");

        lecIdX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecIdXActionPerformed(evt);
            }
        });
        lecIdX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lecIdXKeyTyped(evt);
            }
        });

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel64.setText("Course");

        newadmin3.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        newadmin3.setForeground(new java.awt.Color(0, 0, 102));
        newadmin3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newadmin3.setText("NEW LECTURER FOR POSTGRADUATES");

        courseX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        courseX.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                courseXItemStateChanged(evt);
            }
        });
        courseX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(genderX, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contactnoX, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(birthdateX, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(88, 88, 88)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                    .addComponent(jLabel60, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(facultyX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailX, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fullnameX, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lecIdX, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fyearX, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel56)
                                    .addComponent(jLabel61))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subIdX, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qualifiX, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(instiX, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(subjectX, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yearX, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(courseX, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(78, 78, 78))))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(mainmenuX)
                .addGap(76, 76, 76)
                .addComponent(addX)
                .addGap(57, 57, 57)
                .addComponent(cancelX)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(newadmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newadmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facultyX, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullnameX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fyearX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lecIdX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(courseX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subjectX, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(subIdX, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qualifiX, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instiX, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearX, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(164, 164, 164))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(contactnoX, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birthdateX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mainmenuX)
                            .addComponent(addX)
                            .addComponent(cancelX))
                        .addGap(88, 88, 88))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subjectXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectXActionPerformed

    private void addXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addXActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/logininfo","root","");
            String query = "insert into lecturerdetails(full_name,lecturer_id,e_mail,address,contact_no,birth_date,gender,faculty,for_year,course,subject,subject_code,qualification,institute,year)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, fullnameX.getText());
            pst.setString(2, lecIdX.getText());
            pst.setString(3, emailX.getText());
            pst.setString(4, addressX.getText());
            pst.setString(5, contactnoX.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            birthdateX.setFormats("yyyy-MM-dd");
            String d = sdf.format(birthdateX.getDate());
            pst.setString(6, d);
            String gen;
            gen = genderX.getSelectedItem().toString();
            pst.setString(7, gen);
            String facul;
            facul = facultyX.getSelectedItem().toString();
            pst.setString(8, facul);
            String yr;
            yr = fyearX.getSelectedItem().toString();
            pst.setString(9, yr);
            String cou;
            cou = courseX.getSelectedItem().toString();
            pst.setString(10, cou);
            pst.setString(11, subjectX.getText());
            pst.setString(12, subIdX.getText());
            pst.setString(13, qualifiX.getText());
            pst.setString(14, instiX.getText());
            pst.setInt(15, Integer.parseInt(yearX.getText()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inserted Sucessfully!");

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_addXActionPerformed

    private void emailXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailXActionPerformed

    private void fullnameXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameXActionPerformed

    private void fullnameXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fullnameXKeyTyped
        char enter = evt.getKeyChar();
        if((Character.isDigit(enter))){
            evt.consume();
            JOptionPane.showMessageDialog(null,"Incorrect Name Format");
        }
    }//GEN-LAST:event_fullnameXKeyTyped

    private void contactnoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnoXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnoXActionPerformed

    private void contactnoXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactnoXKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
            JOptionPane.showMessageDialog(null,"Incorrect contact No Format");
        }
    }//GEN-LAST:event_contactnoXKeyTyped

    private void cancelXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelXActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelXActionPerformed

    private void facultyXItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_facultyXItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {
            if(this.facultyX.getSelectedIndex()>=0)
            {
                this.courseX.setModel(new DefaultComboBoxModel(this.getCourse(this.facultyX.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_facultyXItemStateChanged

    private void facultyXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyXActionPerformed

    private void yearXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearXActionPerformed

    private void instiXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instiXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instiXActionPerformed

    private void qualifiXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qualifiXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qualifiXActionPerformed

    private void subIdXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subIdXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subIdXActionPerformed

    private void mainmenuXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuXActionPerformed
        this.hide();
        MainMenu fr = new MainMenu();
        fr.setVisible(true);
    }//GEN-LAST:event_mainmenuXActionPerformed

    private void genderXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderXActionPerformed

    private void fyearXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fyearXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fyearXActionPerformed

    private void lecIdXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecIdXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecIdXActionPerformed

    private void lecIdXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lecIdXKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_lecIdXKeyTyped

    private void courseXItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_courseXItemStateChanged

    }//GEN-LAST:event_courseXItemStateChanged

    private void courseXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseXActionPerformed
    
    public String[] getCourse(String afaculty)
    {
        String[] acourse = new String[2];
        if(afaculty.equalsIgnoreCase("School of Business"))
        {
            acourse[0] = "MSc in Marketing";
            acourse[1] = "MSc in Management";
        }
        
        if(afaculty.equalsIgnoreCase("School of Computing"))
        {
            acourse[0] = "MSc in Computer Networks";
            acourse[1] = "MSc in Computer Security";
        }
        return acourse;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewLecturerForPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewLecturerForPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewLecturerForPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewLecturerForPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewLecturerForPG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add2;
    private javax.swing.JButton add3;
    private javax.swing.JButton add4;
    private javax.swing.JButton addX;
    private javax.swing.JTextArea address;
    private javax.swing.JTextArea address1;
    private javax.swing.JTextArea address2;
    private javax.swing.JTextArea addressX;
    private org.jdesktop.swingx.JXDatePicker birthdate;
    private org.jdesktop.swingx.JXDatePicker birthdate1;
    private org.jdesktop.swingx.JXDatePicker birthdate2;
    private org.jdesktop.swingx.JXDatePicker birthdateX;
    private javax.swing.JButton cancel;
    private javax.swing.JButton cancel1;
    private javax.swing.JButton cancel2;
    private javax.swing.JButton cancelX;
    private javax.swing.JTextField contactno;
    private javax.swing.JTextField contactno1;
    private javax.swing.JTextField contactno2;
    private javax.swing.JTextField contactnoX;
    private javax.swing.JComboBox course;
    private javax.swing.JComboBox course1;
    private javax.swing.JComboBox course2;
    private javax.swing.JComboBox courseX;
    private javax.swing.JTextField email;
    private javax.swing.JTextField email1;
    private javax.swing.JTextField email2;
    private javax.swing.JTextField emailX;
    private javax.swing.JComboBox faculty;
    private javax.swing.JComboBox faculty1;
    private javax.swing.JComboBox faculty2;
    private javax.swing.JComboBox facultyX;
    private javax.swing.JTextField fullname;
    private javax.swing.JTextField fullname1;
    private javax.swing.JTextField fullname2;
    private javax.swing.JTextField fullnameX;
    private javax.swing.JComboBox fyear;
    private javax.swing.JComboBox fyear1;
    private javax.swing.JComboBox fyear2;
    private javax.swing.JComboBox fyearX;
    private javax.swing.JComboBox gender;
    private javax.swing.JComboBox gender1;
    private javax.swing.JComboBox gender2;
    private javax.swing.JComboBox genderX;
    private javax.swing.JTextField insti;
    private javax.swing.JTextField insti1;
    private javax.swing.JTextField insti2;
    private javax.swing.JTextField instiX;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField lecId;
    private javax.swing.JTextField lecId1;
    private javax.swing.JTextField lecId2;
    private javax.swing.JTextField lecIdX;
    private javax.swing.JButton mainmenu;
    private javax.swing.JButton mainmenu1;
    private javax.swing.JButton mainmenu2;
    private javax.swing.JButton mainmenuX;
    private javax.swing.JLabel newadmin;
    private javax.swing.JLabel newadmin1;
    private javax.swing.JLabel newadmin2;
    private javax.swing.JLabel newadmin3;
    private javax.swing.JTextField qualifi;
    private javax.swing.JTextField qualifi1;
    private javax.swing.JTextField qualifi2;
    private javax.swing.JTextField qualifiX;
    private javax.swing.JTextField subId;
    private javax.swing.JTextField subId1;
    private javax.swing.JTextField subId2;
    private javax.swing.JTextField subIdX;
    private javax.swing.JTextField subject;
    private javax.swing.JTextField subject1;
    private javax.swing.JTextField subject2;
    private javax.swing.JTextField subjectX;
    private javax.swing.JTextField year;
    private javax.swing.JTextField year1;
    private javax.swing.JTextField year2;
    private javax.swing.JTextField yearX;
    // End of variables declaration//GEN-END:variables
}
