
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.HashSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pirakavi
 */
public class PGcoursedetails extends javax.swing.JFrame {

    /**
     * Creates new form PGcoursedetails
     */
    public PGcoursedetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        subject = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        course = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        faculty = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        semi1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        subject1 = new javax.swing.JList();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        subject2 = new javax.swing.JList();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        semi2 = new javax.swing.JList();
        right1 = new javax.swing.JButton();
        left1 = new javax.swing.JButton();
        right2 = new javax.swing.JButton();
        left2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        studentid = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        mainmenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        subject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subject.setText("Student Id");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Course");

        course.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        course.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MSc in Marketing", "MSc in Management" }));
        course.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                courseItemStateChanged(evt);
            }
        });
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Selected Subject");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Semester 1");

        faculty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        faculty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "School of Business", "School of Computing" }));
        faculty.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                facultyItemStateChanged(evt);
            }
        });
        faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("year");

        year.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "First year", "Second Year" }));
        year.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearItemStateChanged(evt);
            }
        });
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(semi1);

        jScrollPane2.setViewportView(subject1);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Selected Subject");

        jScrollPane3.setViewportView(subject2);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Semester 2");

        jScrollPane4.setViewportView(semi2);

        right1.setText(">>");
        right1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                right1ActionPerformed(evt);
            }
        });

        left1.setText("<<");
        left1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                left1ActionPerformed(evt);
            }
        });

        right2.setText(">>");
        right2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                right2ActionPerformed(evt);
            }
        });

        left2.setText("<<");
        left2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                left2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("POSTGRADUATES COURSE REGISTRATION");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Faculty");

        register.setBackground(new java.awt.Color(0, 0, 255));
        register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        mainmenu.setBackground(new java.awt.Color(0, 0, 255));
        mainmenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainmenu.setText("MainMenu");
        mainmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(studentid, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(left1)
                                    .addComponent(right1)
                                    .addComponent(right2)
                                    .addComponent(left2))))
                        .addGap(97, 97, 97)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))
                        .addGap(0, 23, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(register)
                .addGap(35, 35, 35)
                .addComponent(mainmenu)
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 231, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(right1)
                                .addGap(18, 18, 18)
                                .addComponent(left1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(right2)
                                        .addGap(28, 28, 28)
                                        .addComponent(left2)
                                        .addGap(25, 25, 25))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register)
                    .addComponent(mainmenu))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultListModel dim = new DefaultListModel(); //Postgraduates semi 1 compulsary subjects
    public String[] getSubject()
    {
        
            String A = "PGB1101";
            String B = "PGB1102";
            String C = "PGB1103";
            String D = "PGB1104";//marketing year 1 seme 1
            String BA = "PGB2101";
            String BB = "PGB2102";
            String BC = "PGB2103";
            String BD = "PGB2104";//marketing year 2 seme 1
        
            String E = "PGB1201";
            String F = "PGB1202";
            String G = "PGB1203";
            String H = "PGB1204";// management year 1 seme 1
            String EA = "PGB2201";
            String EB = "PGB2202";
            String EC = "PGB2203";
            String ED = "PGB2204";// management year 2 seme 1
            
            String M = "PGC1101";
            String N = "PGC1102";
            String O = "PGC1103";
            String P = "PGC1104";//networking year 1 seme 1
            String MA = "PGC2101";
            String MB = "PGC2102";
            String MC = "PGC2103";
            String MD = "PGC2104";//networking year 2 seme 1
            
            
            
            String Q = "PGC1201";
            String R = "PGC1202";
            String S = "PGC1203";
            String T = "PGC1204";//security 1 seme 1
            String PA = "PGC2201";
            String PB = "PGC2202";
            String PC = "PGC2203";
            String PD = "PGC2204";//security 2 seme 1
            
            
           
           
       if (course.getSelectedItem()=="MSc in Marketing" && year.getSelectedItem()=="First year") {
           dim.removeAllElements();
            dim.addElement(A);
            dim.addElement(B);
            dim.addElement(C);
            dim.addElement(D);
            
            subject1.setModel(dim);
    
        }
       
       
       else if (course.getSelectedItem()=="MSc in Marketing" && year.getSelectedItem()=="Second Year") {
           dim.removeAllElements();
            dim.addElement(BA);
            dim.addElement(BB);
            dim.addElement(BC);
            dim.addElement(BD);
            
            subject1.setModel(dim);
        }
       else if (course.getSelectedItem()=="MSc in Management" && year.getSelectedItem()=="First Year") {
           dim.removeAllElements();
            dim.addElement(E);
            dim.addElement(F);
            dim.addElement(G);
            dim.addElement(H);
            
            subject1.setModel(dim);
        }
       
       else if (course.getSelectedItem()=="MSc in Management" && year.getSelectedItem()=="Second Year") {
           dim.removeAllElements();
            dim.addElement(EA);
            dim.addElement(EB);
            dim.addElement(EC);
            dim.addElement(ED);
            
            subject1.setModel(dim);
        }
       
       
        
       else if (course.getSelectedItem()=="MSc in Computer Networks" && year.getSelectedItem()=="First Year") {
           dim.removeAllElements();
            dim.addElement(M);
            dim.addElement(N);
            dim.addElement(0);
            dim.addElement(P);
            
            subject1.setModel(dim);
        }
       
       else if (course.getSelectedItem()=="MSc in Computer Networks" && year.getSelectedItem()=="Second Year") {
           dim.removeAllElements();
            dim.addElement(MA);
            dim.addElement(MB);
            dim.addElement(MC);
            dim.addElement(MD);
            
            subject1.setModel(dim);
        }
		
		else if (course.getSelectedItem()=="MSc in Computer Security" && year.getSelectedItem()=="First Year") {
           dim.removeAllElements();
            dim.addElement(Q);
            dim.addElement(R);
            dim.addElement(T);
            dim.addElement(P);
            
            subject1.setModel(dim);
        }
       
       else if (course.getSelectedItem()=="MSc in Computer Security" && year.getSelectedItem()=="Second Year") {
           dim.removeAllElements();
            dim.addElement(PA);
            dim.addElement(PB);
            dim.addElement(PC);
            dim.addElement(PD);
            
            subject1.setModel(dim);
        }
       
       
        return null;
    
    }
    
    DefaultListModel dim1 = new DefaultListModel(); //Postgraduates semi 1 compulsary subjects
    public String[] getSubject1()
    {
        
            String A1 = "PGB1111";
            String B1 = "PGB1112";
            String C1 = "PGB1113";
            String D1 = "PGB1114";//marketing year 1 seme 1
            String BA1 = "PGB2111";
            String BB1 = "PGB2112";
            String BC1 = "PGB2113";
            String BD1 = "PGB2114";//marketing year 2 seme 1
        
            String E1 = "PGB1211";
            String F1 = "PGB1212";
            String G1 = "PGB1213";
            String H1 = "PGB1214";// management year 1 seme 1
            String EA1 = "PGB2211";
            String EB1 = "PGB2212";
            String EC1 = "PGB2213";
            String ED1 = "PGB2214";// management year 2 seme 1
            
            String M1 = "PGC1111";
            String N1 = "PGC1112";
            String O1= "PGC1113";
            String P1 = "PGC1114";//networking year 1 seme 1
            String MA1 = "PGC2111";
            String MB1 = "PGC2112";
            String MC1 = "PGC2113";
            String MD1 = "PGC2114";//networking year 2 seme 1
            
            
            
            String Q1 = "PGC1211";
            String R1 = "PGC1212";
            String S1 = "PGC1213";
            String T1 = "PGC1214";//security 1 seme 1
            String PA1 = "PGC2211";
            String PB1 = "PGC2212";
            String PC1 = "PGC2213";
            String PD1 = "PGC2214";//security 2 seme 1
            
            
           
           
       if (course.getSelectedItem()=="MSc in Marketing" && year.getSelectedItem()=="First year") {
           dim1.removeAllElements();
            dim1.addElement(A1);
            dim1.addElement(B1);
            dim1.addElement(C1);
            dim1.addElement(D1);
            
            subject2.setModel(dim1);
    
        }
       
       
       else if (course.getSelectedItem()=="MSc in Marketing" && year.getSelectedItem()=="Second Year") {
           dim1.removeAllElements();
            dim1.addElement(BA1);
            dim1.addElement(BB1);
            dim1.addElement(BC1);
            dim1.addElement(BD1);
            
            subject2.setModel(dim1);
        }
       else if (course.getSelectedItem()=="MSc in Management" && year.getSelectedItem()=="First Year") {
           dim1.removeAllElements();
            dim1.addElement(E1);
            dim1.addElement(F1);
            dim1.addElement(G1);
            dim1.addElement(H1);
            
            subject2.setModel(dim1);
        }
       
       else if (course.getSelectedItem()=="MSc in Management" && year.getSelectedItem()=="Second Year") {
           dim1.removeAllElements();
            dim1.addElement(EA1);
            dim1.addElement(EB1);
            dim1.addElement(EC1);
            dim1.addElement(ED1);
            
            subject2.setModel(dim1);
        }
       
       
        
       else if (course.getSelectedItem()=="MSc in Computer Networks" && year.getSelectedItem()=="First Year") {
           dim1.removeAllElements();
            dim1.addElement(M1);
            dim1.addElement(N1);
            dim1.addElement(01);
            dim1.addElement(P1);
            
            subject2.setModel(dim1);
        }
       
       else if (course.getSelectedItem()=="MSc in Computer Networks" && year.getSelectedItem()=="Second Year") {
           dim1.removeAllElements();
            dim1.addElement(MA1);
            dim1.addElement(MB1);
            dim1.addElement(MC1);
            dim1.addElement(MD1);
            
            subject2.setModel(dim1);
        }
		
		else if (course.getSelectedItem()=="MSc in Computer Security" && year.getSelectedItem()=="First Year") {
           dim1.removeAllElements();
            dim1.addElement(Q1);
            dim1.addElement(R1);
            dim1.addElement(T1);
            dim1.addElement(P1);
            
            subject2.setModel(dim1);
        }
       
       else if (course.getSelectedItem()=="MSc in Computer Security" && year.getSelectedItem()=="Second Year") {
           dim1.removeAllElements();
            dim1.addElement(PA1);
            dim1.addElement(PB1);
            dim1.addElement(PC1);
            dim1.addElement(PD1);
            
            subject2.setModel(dim1);
        }
       
       
        return null;
    
    }
    
    DefaultListModel dim2 = new DefaultListModel();//Undergraduates semi 1 selection subjects
    public String[] getSubject2()
    {
            String A11 = "PGB1105";
            String B11 = "PGB1106";
            String C11 = "PGB1107";
            String D11 = "PGB1108";
            String E11 = "PGB1109";//marketing year 1 seme 1
            String BA11 = "PGB2105";
            String BB11 = "PGB2106";
            String BC11 = "PGB2107";
            String BD11 = "PGB2108";
            String BE11 = "PGB2109";
            String BF11= "PGB2110";//marketing year 2 seme 1
           
		   
            String A12 = "PGB1205";
            String B12 = "PGB1206";
            String C12 = "PGB1207";
            String D12 = "PGB1208";
            String E12 = "PGB1209";// management year 1 seme 1
            String BA12 = "PGB2205";
            String BB12 = "PGB2206";
            String BC12 = "PGB2207";
            String BD12 = "PGB2208";
            String BE12 = "PGB2209";
            String BF12 = "PGB2210";// management year 2 seme 1
            
			
            String A14 = "PGC1105";
            String B14 = "PGC1106";
            String C14 = "PGC1107";
            String D14 = "PGC1108";
            String E14 = "PGC1109";
            String F14 = "PGC1110";// networks  year 1 seme 1
            String BA14 = "PGC2105";
            String BB14 = "PGC2106";
            String BC14 = "PGC2107";
            String BD14 = "PGC2108";
            String BE14 = "PGC2109";
            String BF14 = "PGC2110";//  networks year 2 seme 1
            
            String A15 = "PGC1205";
            String B15 = "PGC1206";
            String C15 = "PGC1207";
            String D15 = "PGC1208";
            String E15 = "PGC1209";
            String F15 = "PGC1210";// security year 1 seme 1
            String BA15 = "PGC2205";
            String BB15 = "PGC2206";
            String BC15 = "PGC2207";
            String BD15 = "PGC2208";
            String BE15 = "PGC2209";
            String BF15 = "PGC2210";// security year 2 seme 1
            
            
            if (course.getSelectedItem()=="MSc in Marketing" && year.getSelectedItem()=="First year") {
           dim2.removeAllElements();
            dim2.addElement(A11);
            dim2.addElement(B11);
            dim2.addElement(C11);
            dim2.addElement(D11);
            dim2.addElement(E11);
            
            semi1.setModel(dim2);
    
        }
       
       
       else if (course.getSelectedItem()=="MSc in Marketing" && year.getSelectedItem()=="Second Year") {
           dim2.removeAllElements();
            dim2.addElement(BA11);
            dim2.addElement(BB11);
            dim2.addElement(BC11);
            dim2.addElement(BD11);
            dim2.addElement(BE11);
            dim2.addElement(BF11);
            
            semi1.setModel(dim2);
        }
       else if (course.getSelectedItem()=="MSc in Management" && year.getSelectedItem()=="First Year") {
           dim2.addElement(A12);
            dim2.addElement(B12);
            dim2.addElement(C12);
            dim2.addElement(D12);
            dim2.addElement(E12);
            
            semi1.setModel(dim2);
        }
       
       else if (course.getSelectedItem()=="MSc in Management" && year.getSelectedItem()=="Second Year") {
           dim2.removeAllElements();
            dim2.addElement(BA12);
            dim2.addElement(BB12);
            dim2.addElement(BC12);
            dim2.addElement(BD12);
            dim2.addElement(BE12);
            dim2.addElement(BF12);
            
            semi1.setModel(dim2);
        }
       
       
        
       else if (course.getSelectedItem()=="MSc in Computer Networks" && year.getSelectedItem()=="First Year") {
           dim2.addElement(A14);
            dim2.addElement(B14);
            dim2.addElement(C14);
            dim2.addElement(D14);
            dim2.addElement(E14);
            dim2.addElement(F14);

            
            semi1.setModel(dim2);
        }
       
       else if (course.getSelectedItem()=="MSc in Computer Networks" && year.getSelectedItem()=="Second Year") {
           dim2.removeAllElements();
            dim2.addElement(BA14);
            dim2.addElement(BB14);
            dim2.addElement(BC14);
            dim2.addElement(BD14);
            dim2.addElement(BE14);
            dim2.addElement(BF14);
            
            semi1.setModel(dim2);
        }
		
		else if (course.getSelectedItem()=="MSc in Computer Security" && year.getSelectedItem()=="First Year") {
           dim2.addElement(A15);
            dim2.addElement(B15);
            dim2.addElement(C15);
            dim2.addElement(D15);
            dim2.addElement(E15);
            dim2.addElement(F15);
            
            semi1.setModel(dim2);
        }
       
       else if (course.getSelectedItem()=="MSc in Computer Security" && year.getSelectedItem()=="Second Year") {
           dim2.removeAllElements();
            dim2.addElement(BA15);
            dim2.addElement(BB15);
            dim2.addElement(BC15);
            dim2.addElement(BD15);
            dim2.addElement(BE15);
            dim2.addElement(BF15);
            semi1.setModel(dim2);
        }
       
       
        return null;
    }
    
    DefaultListModel dim3 = new DefaultListModel();//Undergraduates semi 1 selection subjects
    public String[] getSubject3()
    {
            String Ax11 = "PGB1115";
            String Bx11 = "PGB1116";
            String Cx11 = "PGB1117";
            String Dx11 = "PGB1118";
            String Ex11 = "PGB1119";//marketing year 1 seme 1
            String BAx11 = "PGB2115";
            String BBx11 = "PGB2116";
            String BCx11 = "PGB2117";
            String BDx11 = "PGB2118";
            String BEx11 = "PGB2119";
            String BFx11= "PGB2120";//marketing year 2 seme 1
           
		   
            String Ax12 = "PGB1215";
            String Bx12 = "PGB1216";
            String Cx12 = "PGB1217";
            String Dx12 = "PGB1218";
            String Ex12 = "PGB1219";// management year 1 seme 1
            String BAx12 = "PGB2215";
            String BBx12 = "PGB2216";
            String BCx12 = "PGB2217";
            String BDx12 = "PGB2218";
            String BEx12 = "PGB2219";
            String BFx12 = "PGB2220";// management year 2 seme 1
            
			
            String Ax14 = "PGC1115";
            String Bx14 = "PGC1116";
            String Cx14 = "PGC1117";
            String Dx14 = "PGC1118";
            String Ex14 = "PGC1119";
            String Fx14 = "PGC1111";// networks  year 1 seme 1
            String BAx14 = "PGC2115";
            String BBx14 = "PGC2116";
            String BCx14 = "PGC2117";
            String BDx14 = "PGC2118";
            String BEx14 = "PGC2119";
            String BFx14 = "PGC2120";//  networks year 2 seme 1
            
            String Ax15 = "PGC1215";
            String Bx15 = "PGC1216";
            String Cx15 = "PGC1217";
            String Dx15 = "PGC1218";
            String Ex15 = "PGC1219";
            String Fx15 = "PGC1211";// security year 1 seme 1
            String BAx15 = "PGC2215";
            String BBx15 = "PGC2216";
            String BCx15 = "PGC2217";
            String BDx15 = "PGC2218";
            String BEx15 = "PGC2219";
            String BFx15 = "PGC2220";// security year 2 seme 1
            
            
            if (course.getSelectedItem()=="MSc in Marketing" && year.getSelectedItem()=="First year") {
           dim3.removeAllElements();
            dim3.addElement(Ax11);
            dim3.addElement(Bx11);
            dim3.addElement(Cx11);
            dim3.addElement(Dx11);
            dim3.addElement(Ex11);
            
            semi2.setModel(dim3);
    
        }
       
       
       else if (course.getSelectedItem()=="MSc in Marketing" && year.getSelectedItem()=="Second Year") {
           dim3.removeAllElements();
            dim3.addElement(BAx11);
            dim3.addElement(BBx11);
            dim3.addElement(BCx11);
            dim3.addElement(BDx11);
            dim3.addElement(BEx11);
            dim3.addElement(BFx11);
            
            semi2.setModel(dim3);
        }
       else if (course.getSelectedItem()=="MSc in Management" && year.getSelectedItem()=="First Year") {
           dim3.addElement(Ax12);
            dim3.addElement(Bx12);
            dim3.addElement(Cx12);
            dim3.addElement(Dx12);
            dim3.addElement(Ex12);
            
            semi2.setModel(dim3);
        }
       
       else if (course.getSelectedItem()=="MSc in Management" && year.getSelectedItem()=="Second Year") {
           dim3.removeAllElements();
            dim3.addElement(BAx12);
            dim3.addElement(BBx12);
            dim3.addElement(BCx12);
            dim3.addElement(BDx12);
            dim3.addElement(BEx12);
            dim3.addElement(BFx12);
            
            semi2.setModel(dim3);
        }
       
       
        
       else if (course.getSelectedItem()=="MSc in Computer Networks" && year.getSelectedItem()=="First Year") {
           dim3.addElement(Ax14);
            dim3.addElement(Bx14);
            dim3.addElement(Cx14);
            dim3.addElement(Dx14);
            dim3.addElement(Ex14);
            dim3.addElement(Fx14);

            
            semi2.setModel(dim3);
        }
       
       else if (course.getSelectedItem()=="MSc in Computer Networks" && year.getSelectedItem()=="Second Year") {
           dim3.removeAllElements();
            dim3.addElement(BAx14);
            dim3.addElement(BBx14);
            dim3.addElement(BCx14);
            dim3.addElement(BDx14);
            dim3.addElement(BEx14);
            dim3.addElement(BFx14);
            
            semi2.setModel(dim3);
        }
		
		else if (course.getSelectedItem()=="MSc in Computer Security" && year.getSelectedItem()=="First Year") {
           dim3.addElement(Ax15);
            dim3.addElement(Bx15);
            dim3.addElement(Cx15);
            dim3.addElement(Dx15);
            dim3.addElement(Ex15);
            dim3.addElement(Fx15);
            
            semi2.setModel(dim3);
        }
       
       else if (course.getSelectedItem()=="MSc in Computer Security" && year.getSelectedItem()=="Second Year") {
           dim3.removeAllElements();
            dim3.addElement(BAx15);
            dim3.addElement(BBx15);
            dim3.addElement(BCx15);
            dim3.addElement(BDx15);
            dim3.addElement(BEx15);
            dim3.addElement(BFx15);
            semi2.setModel(dim3);
        }
       
       
        return null;
    }

    
    
    private void courseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_courseItemStateChanged

        getSubject();
        getSubject1();
        getSubject2();
        getSubject3();

    }//GEN-LAST:event_courseItemStateChanged

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseActionPerformed

    public String[] getCourse(String afaculty)
    {
        String[] acourse = new String[2];
        if(afaculty.equalsIgnoreCase("School of Business"))
        {
            acourse[0] = "MSc in Marketing";
            acourse[1] = "MSc in Management";
            
        }
        
        if(afaculty.equalsIgnoreCase("School of Computing"))
        {
            acourse[0] = "MSc in Computer Networks";
            acourse[1] = "MSc in Computer Security";
           
        }
        
        return acourse;
    }

    
    private void facultyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_facultyItemStateChanged

        getSubject();
        getSubject1();
        getSubject2();
        getSubject3();
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {
            if(this.faculty.getSelectedIndex()>=0)
            {
                this.course.setModel(new DefaultComboBoxModel(this.getCourse(this.faculty.getSelectedItem().toString())));
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_facultyItemStateChanged

    private void facultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyActionPerformed

    private void yearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearItemStateChanged

        getSubject();
        getSubject1();
        getSubject2();
        getSubject3();// TODO add your handling code here:
    }//GEN-LAST:event_yearItemStateChanged

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed
    DefaultListModel dim4 = new DefaultListModel();
    private void right1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_right1ActionPerformed
           if(subject1.getSelectedValue()=="PGB1101" || subject1.getSelectedValue()=="PGB1102" || subject1.getSelectedValue()=="PGB1103" || subject1.getSelectedValue()=="PGB1104" ||
                subject1.getSelectedValue()=="PGB2101" || subject1.getSelectedValue()=="PGB2102" || subject1.getSelectedValue()=="PGB2103" || subject1.getSelectedValue()=="PGB2104" ||
                subject1.getSelectedValue()=="PGB3101" || subject1.getSelectedValue()=="PGB3102" || subject1.getSelectedValue()=="PGB3103" || subject1.getSelectedValue()=="PGB3104" ||
                subject1.getSelectedValue()=="PGB4101" || subject1.getSelectedValue()=="PGB4102" || subject1.getSelectedValue()=="PGB4103" || subject1.getSelectedValue()=="PGB4104" )//Marketing
        {
            JOptionPane.showMessageDialog(null,"This Subject Can't Move!!!");
            return;
        }
        
        else if(subject1.getSelectedValue()=="PGB1201" || subject1.getSelectedValue()=="PGB1202" || subject1.getSelectedValue()=="PGB1203" || subject1.getSelectedValue()=="PGB1204" ||
                subject1.getSelectedValue()=="PGB2201" || subject1.getSelectedValue()=="PGB2202" || subject1.getSelectedValue()=="PGB2203" || subject1.getSelectedValue()=="PGB2204" ||
                subject1.getSelectedValue()=="PGB3201" || subject1.getSelectedValue()=="PGB3202" || subject1.getSelectedValue()=="PGB3203" || subject1.getSelectedValue()=="PGB3204" ||
                subject1.getSelectedValue()=="PGB4201" || subject1.getSelectedValue()=="PGB4202" || subject1.getSelectedValue()=="PGB4203" || subject1.getSelectedValue()=="PGB4204" )// Management
        {
            JOptionPane.showMessageDialog(null,"This Subject Can't Move!!!");
            return;
        }
           
         if(subject1.getSelectedValue()=="PGC1101" || subject1.getSelectedValue()=="PGC1102" || subject1.getSelectedValue()=="PGC1103" || subject1.getSelectedValue()=="PGC1104" ||
                subject1.getSelectedValue()=="PGC2101" || subject1.getSelectedValue()=="PGC2102" || subject1.getSelectedValue()=="PGC2103" || subject1.getSelectedValue()=="PGC2104" ||
                subject1.getSelectedValue()=="PGC3101" || subject1.getSelectedValue()=="PGC3102" || subject1.getSelectedValue()=="PGC3103" || subject1.getSelectedValue()=="PGC3104" ||
                subject1.getSelectedValue()=="PGC4101" || subject1.getSelectedValue()=="PGC4102" || subject1.getSelectedValue()=="PGC4103" || subject1.getSelectedValue()=="PGC4104" )//Business Management
        {
            JOptionPane.showMessageDialog(null,"This Subject Can't Move!!!");
            return;
        }
        
        else if(subject1.getSelectedValue()=="PGC1201" || subject1.getSelectedValue()=="PGC1202" || subject1.getSelectedValue()=="PGC1203" || subject1.getSelectedValue()=="PGC1204" ||
                subject1.getSelectedValue()=="PGC2201" || subject1.getSelectedValue()=="PGC2202" || subject1.getSelectedValue()=="PGC2203" || subject1.getSelectedValue()=="PGC2204" ||
                subject1.getSelectedValue()=="PGC3201" || subject1.getSelectedValue()=="PGC3202" || subject1.getSelectedValue()=="PGC203" || subject1.getSelectedValue()=="PGC3204" ||
                subject1.getSelectedValue()=="PGC4201" || subject1.getSelectedValue()=="PGC4202" || subject1.getSelectedValue()=="PGC4203" || subject1.getSelectedValue()=="PGC4204" )// Management
        {
            JOptionPane.showMessageDialog(null,"This Subject Can't Move!!!");
            return;
        }
        
        /*dim3.addElement(subject1.getSelectedValue());
        semi1.setModel(dim3);
        dim.removeElementAt(subject1.getSelectedIndex());*/

        //subject1.setSelectedIndex(-1);
        //subject1.ensureIndexIsVisible(-1);
        // TODO add your handling code here:
    }//GEN-LAST:event_right1ActionPerformed

    private void left1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_left1ActionPerformed
        //dim2.addElement(subject1.getSelectedValue());
        /*dim.addElement(semi1.getSelectedValue());
        subject1.setModel(dim);
        dim3.removeElementAt(semi1.getSelectedIndex());*/
    }//GEN-LAST:event_left1ActionPerformed

    private void right2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_right2ActionPerformed
        /*dim5.addElement(subject2.getSelectedValue());
        semi2.setModel(dim5);
        dim2.removeElementAt(subject2.getSelectedIndex());// TODO add your handling code here:*/
    }//GEN-LAST:event_right2ActionPerformed

    private void left2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_left2ActionPerformed
        /*dim2.addElement(semi1.getSelectedValue());
        subject2.setModel(dim2);
        dim5.removeElementAt(semi2.getSelectedIndex());// TODO add your handling code here:*/
    }//GEN-LAST:event_left2ActionPerformed

    private void mainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuActionPerformed
        this.hide();
        MainMenu k2 = new MainMenu();
        k2.setVisible(true);
    }//GEN-LAST:event_mainmenuActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/logininfo","root","");
            String query = "insert into pgstucourse(student_id,faculty,academic_year,course,sub_semi1,sub_semi2)values(?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            
            pst.setString(1, studentid.getText());
            String fac = faculty.getSelectedItem().toString();
            pst.setString(2, fac);
            String ye = year.getSelectedItem().toString();
            pst.setString(3, ye);
            String cou = course.getSelectedItem().toString();
            pst.setString(4, cou);
            
            int itemIx = subject1.getLastVisibleIndex();
            int n=0;
            subject1.setSelectionInterval(n, itemIx);
            String semione = subject1.getSelectedValuesList().toString();
            pst.setString(5, semione);
            
            int itemx = subject2.getLastVisibleIndex();
            int m=0;
            subject2.setSelectionInterval(m, itemx);
            String semitwo = subject2.getSelectedValuesList().toString();
            pst.setString(6, semitwo);
            
            pst.executeUpdate();
            subject1.clearSelection();
            subject2.clearSelection();
            
            JOptionPane.showMessageDialog(null,"Inserted Sucessfully!");
            
           
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PGcoursedetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PGcoursedetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PGcoursedetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PGcoursedetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PGcoursedetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox course;
    private javax.swing.JComboBox faculty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton left1;
    private javax.swing.JButton left2;
    private javax.swing.JButton mainmenu;
    private javax.swing.JButton register;
    private javax.swing.JButton right1;
    private javax.swing.JButton right2;
    private javax.swing.JList semi1;
    private javax.swing.JList semi2;
    private javax.swing.JTextField studentid;
    private javax.swing.JLabel subject;
    private javax.swing.JList subject1;
    private javax.swing.JList subject2;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables

    
}
