
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pirakavi
 */
public class PGResult extends javax.swing.JFrame {

    int t1, t2, t3;
    /**
     * Creates new form UGResult
     */
    public PGResult() {
        initComponents();
        view();
        view1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        subject = new javax.swing.JLabel();
        course = new javax.swing.JComboBox();
        faculty = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        studentid = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        mainmenu = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_display = new javax.swing.JTable();
        subject1 = new javax.swing.JLabel();
        marks = new javax.swing.JTextField();
        sub = new javax.swing.JTextField();
        subject2 = new javax.swing.JLabel();
        subject3 = new javax.swing.JLabel();
        credit1 = new javax.swing.JTextField();
        subject4 = new javax.swing.JLabel();
        marks1 = new javax.swing.JTextField();
        go_marks = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        credit_marks = new javax.swing.JList();
        go_credit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        credits = new javax.swing.JList();
        subject5 = new javax.swing.JLabel();
        marks2 = new javax.swing.JTextField();
        subject7 = new javax.swing.JLabel();
        credit2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        gpa = new javax.swing.JTextField();
        register1 = new javax.swing.JButton();
        mainmenu1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        credit3 = new javax.swing.JTextField();
        semi = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_display1 = new javax.swing.JTable();
        go_final = new javax.swing.JButton();
        gpabu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        subject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subject.setText("Student Id");

        course.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        course.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BSc in Business Management", "BSc in Management", "BSc in Margeting Management" }));
        course.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                courseItemStateChanged(evt);
            }
        });
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });

        faculty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        faculty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "School of Business", "School of Computing", "School of Engineering" }));
        faculty.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                facultyItemStateChanged(evt);
            }
        });
        faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Semester");

        year.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "First year", "Second Year", "Third Year", "Fourth Year" }));
        year.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearItemStateChanged(evt);
            }
        });
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Faculty");

        studentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentidActionPerformed(evt);
            }
        });
        studentid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                studentidKeyReleased(evt);
            }
        });

        register.setBackground(new java.awt.Color(0, 0, 255));
        register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        register.setText("Update");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        mainmenu.setBackground(new java.awt.Color(0, 0, 255));
        mainmenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainmenu.setText("MainMenu");
        mainmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuActionPerformed(evt);
            }
        });

        table_display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_display.setEditingColumn(0);
        table_display.setEditingRow(0);
        table_display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_displayMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_display);

        subject1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subject1.setText("Subject Id");

        marks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marksActionPerformed(evt);
            }
        });
        marks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                marksKeyReleased(evt);
            }
        });

        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        sub.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                subKeyReleased(evt);
            }
        });

        subject2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subject2.setText("Final Marks");

        subject3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subject3.setText("Marks  X  Credits");

        credit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credit1ActionPerformed(evt);
            }
        });
        credit1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                credit1KeyReleased(evt);
            }
        });

        subject4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subject4.setText("Credits");

        marks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks1ActionPerformed(evt);
            }
        });
        marks1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                marks1KeyReleased(evt);
            }
        });

        go_marks.setBackground(new java.awt.Color(0, 0, 255));
        go_marks.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        go_marks.setText("GO");
        go_marks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_marksActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(credit_marks);

        go_credit.setBackground(new java.awt.Color(0, 0, 255));
        go_credit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        go_credit.setText("GO");
        go_credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_creditActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(credits);

        subject5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subject5.setText("Total (Marks  X  Credits)");

        marks2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks2ActionPerformed(evt);
            }
        });
        marks2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                marks2KeyReleased(evt);
            }
        });

        subject7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subject7.setText("Total Credits");

        credit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credit2ActionPerformed(evt);
            }
        });
        credit2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                credit2KeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Course");

        gpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpaActionPerformed(evt);
            }
        });
        gpa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gpaKeyReleased(evt);
            }
        });

        register1.setBackground(new java.awt.Color(0, 0, 255));
        register1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        register1.setText("Register");
        register1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register1ActionPerformed(evt);
            }
        });

        mainmenu1.setBackground(new java.awt.Color(0, 0, 255));
        mainmenu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainmenu1.setText("MainMenu");
        mainmenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainmenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenu1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("year");

        semi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semiActionPerformed(evt);
            }
        });
        semi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                semiKeyReleased(evt);
            }
        });

        table_display1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "subject_id", "subject_name", "fees", "credit"
            }
        ));
        table_display1.setEditingColumn(0);
        table_display1.setEditingRow(0);
        table_display1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_display1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table_display1);

        go_final.setBackground(new java.awt.Color(0, 0, 255));
        go_final.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        go_final.setText("GO");
        go_final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_finalActionPerformed(evt);
            }
        });

        gpabu.setBackground(new java.awt.Color(0, 0, 255));
        gpabu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gpabu.setText("GPA");
        gpabu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpabuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("POSTGRADUATES RESULTS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(487, 487, 487)
                        .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(subject1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(subject4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(credit1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(go_credit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(subject2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(marks, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(subject3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(marks1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(go_marks, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(go_final, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subject7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(credit2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1548, 1548, 1548))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subject5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(marks2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gpa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gpabu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(register)
                                        .addGap(35, 35, 35)
                                        .addComponent(mainmenu)
                                        .addGap(245, 245, 245))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(459, 459, 459)
                                        .addComponent(register1)
                                        .addGap(29, 29, 29)
                                        .addComponent(mainmenu1)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(studentid, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(374, 374, 374)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(semi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(credit3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(studentid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(subject7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(credit2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(register)
                            .addComponent(mainmenu))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subject1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(credit1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subject4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(go_credit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(marks, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(go_final))
                                            .addComponent(subject2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(subject3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(marks1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(go_marks))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(subject5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(marks2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addComponent(gpabu)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(gpa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(register1)
                                    .addComponent(mainmenu1))
                                .addGap(27, 27, 27))))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(credit3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1083, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void view()
    {
    DefaultTableModel tbl=(DefaultTableModel)table_display.getModel();
        tbl.setRowCount(0);

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/logininfo","root","");
            String a= "'"+studentid.getText().toString()+"'";
            String sql="select * from pgstucourse where student_id like ?";
            //String sql="SELECT * FROM undergraduatestudent Where student_id"+'UG/2017/F001';
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1, studentid.getText() + "%");
            ResultSet result_s=pst.executeQuery();
            String col_name2[]={"Student Id","Faculty","year","Course","Sub Semester 1","Sub Semester 2"};
            tbl.setColumnIdentifiers(col_name2);
            ResultSetMetaData RS=result_s.getMetaData();
            int cols1=RS.getColumnCount();
            while(result_s.next()){
                Object[] obj2=new Object[cols1];
                int i;
                for(i=0;i<cols1;i++){
                    obj2[i]=result_s.getObject(i+1);

                }
                tbl.addRow(obj2);

            }
            //stdId.setText("");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);}
    }
    
    public void view1()
    {
    DefaultTableModel tbl=(DefaultTableModel)table_display1.getModel();
        tbl.setRowCount(0);

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/logininfo","root","");
            String a= "'"+sub.getText().toString()+"'";
            String sql="select * from subjectdetails where sub_id like ?";
            //String sql="SELECT * FROM undergraduatestudent Where student_id"+'UG/2017/F001';
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1, sub.getText() + "%");
            ResultSet result_s=pst.executeQuery();
            String col_name2[]={"faculty","course","sub_name","sub_id","type","academic_year","semester","sub_credits","fees","lecturer"};
            tbl.setColumnIdentifiers(col_name2);
            ResultSetMetaData RS=result_s.getMetaData();
            int cols1=RS.getColumnCount();
            while(result_s.next()){
                Object[] obj2=new Object[cols1];
                int i;
                for(i=0;i<cols1;i++){
                    obj2[i]=result_s.getObject(i+1);

                }
                tbl.addRow(obj2);

            }
            //stdId.setText("");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);}
    }
    
    private void formWindowActivated(java.awt.event.KeyEvent evt){
        t1 = 0;
        t2 = 0;
        t3 =1;
        
    }
    
    private void courseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_courseItemStateChanged

        /*getSubject();
        getSubject1();
        getSubject2();
        getSubject3();*/
    }//GEN-LAST:event_courseItemStateChanged

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseActionPerformed

    private void facultyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_facultyItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {
            if(this.faculty.getSelectedIndex()>=0)
            {
                this.course.setModel(new DefaultComboBoxModel(this.getCourse(this.faculty.getSelectedItem().toString())));
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_facultyItemStateChanged

    private void facultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyActionPerformed

    private void yearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_yearItemStateChanged

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void studentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentidActionPerformed

    private void studentidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentidKeyReleased

        view();
        // TODO add your handling code here:
    }//GEN-LAST:event_studentidKeyReleased

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed

        DefaultListModel sem1 = new DefaultListModel();

       
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/logininfo","root","");
            int row = table_display.getSelectedRow();
            TableModel model = table_display.getModel();
            String tblclick = "'"+model.getValueAt(row, 0).toString()+"'";

            String sql = "select * from pgstucourse where student_id ="+tblclick;
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs = pst.executeQuery();

            if(rs.next())
            {
                String a= "'"+studentid.getText().toString()+"'";
                //a = rs.getString("full_name");
                //ne.fullname.setText(a);

                a = rs.getString("student_id");
                studentid.setText(a);
                a = rs.getString("faculty");
                faculty.setSelectedItem(a);
                a = rs.getString("course");
                course.setSelectedItem(a);

            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_registerActionPerformed

    private void mainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuActionPerformed
        this.hide();
        MainMenu k2 = new MainMenu();
        k2.setVisible(true);
    }//GEN-LAST:event_mainmenuActionPerformed

    private void table_displayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_displayMouseClicked

        DefaultListModel sem1 = new DefaultListModel();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/logininfo","root","");
            int row = table_display.getSelectedRow();
            TableModel model = table_display.getModel();
            String tblclick = "'"+model.getValueAt(row, 0).toString()+"'";

            String sql = "select * from pgstucourse where student_id ="+tblclick;
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs = pst.executeQuery();

            if(rs.next())
            {
                String a= "'"+studentid.getText().toString()+"'";
                /*a = rs.getString("full_name");
                ne.fullname.setText(a);*/

                a = rs.getString("student_id");
                studentid.setText(a);
                a = rs.getString("faculty");
                faculty.setSelectedItem(a);
                a = rs.getString("course");
                course.setSelectedItem(a);
                

            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_table_displayMouseClicked

    private void marksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marksActionPerformed

    private void marksKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marksKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_marksKeyReleased

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subActionPerformed

    private void subKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subKeyReleased
        view1();
    }//GEN-LAST:event_subKeyReleased

    private void credit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_credit1ActionPerformed

    private void credit1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_credit1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_credit1KeyReleased

    private void marks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks1ActionPerformed

    private void marks1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marks1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_marks1KeyReleased

    DefaultListModel Number = new DefaultListModel();
    private void go_marksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_marksActionPerformed
        int num1 = Integer.parseInt(marks1.getText());
        Number.addElement(num1);
        credit_marks.setModel(Number);
        t1 = t1 + num1;
        //total_fees = total_fees + num1;
        
        marks2.setText(Integer.toString(t1));
    }//GEN-LAST:event_go_marksActionPerformed

    DefaultListModel Number1 = new DefaultListModel();
    private void go_creditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_creditActionPerformed
        int num2 = Integer.parseInt(credit1.getText());
        Number1.addElement(num2);
        credits.setModel(Number1);
        t2 = t2 + num2;
        //total_fees = total_fees + num1;
        
        credit2.setText(Integer.toString(t2));
    }//GEN-LAST:event_go_creditActionPerformed

    private void marks2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks2ActionPerformed

    private void marks2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marks2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_marks2KeyReleased

    private void credit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_credit2ActionPerformed

    private void credit2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_credit2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_credit2KeyReleased

    private void gpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpaActionPerformed

    private void gpaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gpaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_gpaKeyReleased

    private void register1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register1ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/logininfo","root","");
            String query = "insert into results(student_id,faculty,year,course,semester,tot_credits,gpa)values(?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);

            String stu =studentid.getText();
            pst.setString(1, stu);
            String fac = faculty.getSelectedItem().toString();
            pst.setString(2, fac);
            String ye = year.getSelectedItem().toString();
            pst.setString(3, ye);
            String cou = course.getSelectedItem().toString();
            pst.setString(4, cou);
            int semi1=Integer.parseInt(semi.getText());
            pst.setInt(5, semi1);
            int credit01=Integer.parseInt(credit2.getText());
            pst.setInt(6, credit01);
            String gpa1=gpa.getText();
            pst.setString(7, gpa1);
            pst.executeUpdate();
            
            
            JOptionPane.showMessageDialog(null,"Inserted Sucessfully!");

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_register1ActionPerformed

    private void mainmenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenu1ActionPerformed
        this.hide();
        MainMenu k2 = new MainMenu();
        k2.setVisible(true);
    }//GEN-LAST:event_mainmenu1ActionPerformed

    private void semiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semiActionPerformed

    private void semiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_semiKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_semiKeyReleased

    private void table_display1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_display1MouseClicked
        DefaultListModel sem1 = new DefaultListModel();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/logininfo","root","");
            int row = table_display1.getSelectedRow();
            TableModel model = table_display1.getModel();
            String tblclick = "'"+model.getValueAt(row, 0).toString()+"'";

            String sql = "select * from subjectdetails where sub_id ="+tblclick;
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs = pst.executeQuery();

            if(rs.next())
            {
                String a= "'"+sub.getText().toString()+"'";
                /*a = rs.getString("full_name");
                ne.fullname.setText(a);*/

                a = rs.getString("sub_id");
                sub.setText(a);
                

            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_table_display1MouseClicked

    
    private void go_finalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_finalActionPerformed
        int numX = Integer.parseInt(marks.getText());
        int numY = Integer.parseInt(credit1.getText());
        int numZ = numX * numY;
       
        marks1.setText(Integer.toString(numZ));
    }//GEN-LAST:event_go_finalActionPerformed

    private void gpabuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpabuActionPerformed
        double numx = Double.parseDouble(marks2.getText());
        double numy = Double.parseDouble(credit2.getText());
        double numz = numx / numy;
       
        gpa.setText(Double.toString(numz));
    }//GEN-LAST:event_gpabuActionPerformed

    public String[] getCourse(String afaculty)
    {
        String[] acourse = new String[3];
        if(afaculty.equalsIgnoreCase("School of Business"))
        {
            acourse[0] = "BSc in Business Management";
            acourse[1] = "BSc in Management";
            acourse[2] = "BSc in Margeting Management";
        }
        
        if(afaculty.equalsIgnoreCase("School of Computing"))
        {
            acourse[0] = "BSc in Computer Science";
            acourse[1] = "BSc in Information Systems";
            acourse[2] = "BSc in Information Technology";
        }
        
        if(afaculty.equalsIgnoreCase("School of Engineering"))
        {
            acourse[0] = "BSc in Civil Engineering";
            acourse[1] = "BSc in Mechanical Engineering";
            acourse[2] = "BSc in Electrical Engineering";
        }
        
        return acourse;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UGResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UGResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UGResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UGResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UGResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox course;
    private javax.swing.JTextField credit1;
    private javax.swing.JTextField credit2;
    private javax.swing.JTextField credit3;
    private javax.swing.JList credit_marks;
    private javax.swing.JList credits;
    private javax.swing.JComboBox faculty;
    private javax.swing.JButton go_credit;
    private javax.swing.JButton go_final;
    private javax.swing.JButton go_marks;
    private javax.swing.JTextField gpa;
    private javax.swing.JButton gpabu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton mainmenu;
    private javax.swing.JButton mainmenu1;
    private javax.swing.JTextField marks;
    private javax.swing.JTextField marks1;
    private javax.swing.JTextField marks2;
    private javax.swing.JButton register;
    private javax.swing.JButton register1;
    private javax.swing.JTextField semi;
    private javax.swing.JTextField studentid;
    private javax.swing.JTextField sub;
    private javax.swing.JLabel subject;
    private javax.swing.JLabel subject1;
    private javax.swing.JLabel subject2;
    private javax.swing.JLabel subject3;
    private javax.swing.JLabel subject4;
    private javax.swing.JLabel subject5;
    private javax.swing.JLabel subject7;
    private javax.swing.JTable table_display;
    private javax.swing.JTable table_display1;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables

    
}
